apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: oci://ghcr.io/prometheus-community/charts
    chart: kube-prometheus-stack
    targetRevision: 79.7.1
    helm:
      valueFiles:
        - $values/helm-values/prometheus-stack-values.yaml
  - repoURL: https://github.com/tobiasfuhge/data-engineering-project.git
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-stack

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
