apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-to-argo-metrics
  namespace: argo-workflows
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: workflow-controller
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: prometheus-stack
    ports:
    - protocol: TCP
      port: 9090
