auth:
  existingSecret: postgres-admin
  database: ds_db
  username: mlops
  secretKeys:
    userPasswordKey: postgres-password

persistence:
  enabled: true
  size: 10Gi
  storageClass: "local-path"

service:
  type: ClusterIP
  port: 5432

initdb:
  scripts:
    create_dbs.sql: |
      CREATE DATABASE airflow_db;
      CREATE DATABASE mlflow_db;
      GRANT ALL PRIVILEGES ON DATABASE airflow_db TO mlops;
      GRANT ALL PRIVILEGES ON DATABASE mlflow_db TO mlops;