renovate:
  config: |
    {
      "platform": "github",
      "token": "{{ .Env.GITHUB_TOKEN }}",
      "repositories": ["tobiasfuhge/data-engineering-project"]
    }
  configEnableHelmTpl: true

envList:
  - name: GITHUB_TOKEN
    valueFrom:
      secretKeyRef:
        name: renovate-git-token
        key: token
