renovate:
  config: |
    {
      "platform": "github",
      "token": "${GITHUB_TOKEN}",
      "repositories": ["tobiasfuhge/data-engineering-project"]
    }

env:
  - name: GITHUB_TOKEN
    valueFrom:
      secretKeyRef:
        name: renovate-git-token
        key: token
